name: increment_decrement_form_field
description: Increment or decrement a value using spaced horizontal icon buttons
version: 1.0.0
repository: https://github.com/Honeyman-Applications/increment_decrement_form_field

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: